package org.leon.finch.dal.foo;

import lombok.Data;
import lombok.EqualsAndHashCode;
import org.leon.finch.dal.base.BaseEntity;

/**
 * generated by SnailGenerator
 *
 * @author Leon Song
 */
@EqualsAndHashCode(callSuper = true)
@Data
public class Foo extends BaseEntity {

    private String name;

    private Integer age;

}
