package org.leon.finch.dal.foo;

import lombok.Data;
import lombok.EqualsAndHashCode;
import org.leon.finch.dal.base.BaseEntity;

/**
 * 傻子表
 *
 * generated by SnailGenerator
 *
 * @author Leon Song
 */
@EqualsAndHashCode(callSuper = true)
@Data
public class Foo extends BaseEntity {

    /**
     * 姓名
     */
    private String name;

    /**
     * 年龄
     */
    private Integer age;

}
